// examples/react-example/App.tsx
import { useState, useEffect } from 'react';
import { Button, Table, Card, Form } from '@ldesign/webcomponent-react';
import type { TableProps } from '@ldesign/webcomponent-react';

function App() {
  const [dataSource, setDataSource] = useState<any[]>([]);

  const columns = [
    { key: 'id', title: 'ID', width: 60, sortable: true },
    { key: 'name', title: '姓名', sortable: true },
    { key: 'age', title: '年龄', width: 80, sortable: true },
    { key: 'email', title: '邮箱' }
  ];

  // 生成测试数据
  useEffect(() => {
    const data = Array.from({ length: 5000 }, (_, i) => ({
      id: i + 1,
      name: `用户 ${i + 1}`,
      age: 20 + (i % 40),
      email: `user${i + 1}@example.com`
    }));
    setDataSource(data);
  }, []);

  const handleButtonClick = () => {
    alert('按钮被点击！');
  };

  const handleSort = (sort: { key: string; order: 'asc' | 'desc' }) => {
    console.log('排序:', sort);
  };

  const handleFormSubmit = (values: Record<string, any>) => {
    console.log('表单提交:', values);
    alert('提交成功！');
  };

  return (
    <div className="app" style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
      <h1 style={{ color: 'var(--ld-color-primary)' }}>
        LDesign WebComponent - React 示例
      </h1>

      {/* 按钮示例 */}
      <Card title="按钮示例">
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
          <Button type="primary" onClick={handleButtonClick}>
            Primary
          </Button>
          <Button type="success">Success</Button>
          <Button type="warning">Warning</Button>
          <Button type="danger">Danger</Button>
          <Button type="primary" loading={true}>Loading</Button>
        </div>
      </Card>

      {/* 表格示例 */}
      <Card title="数据表格（虚拟滚动 5000 行）" style={{ marginTop: '24px' }}>
        <Table
          columns={columns}
          dataSource={dataSource}
          bordered={true}
          striped={true}
          virtual={true}
          height={400}
          rowHeight={48}
          onSort={handleSort}
        />
      </Card>

      {/* 表单示例 */}
      <Card title="表单示例" style={{ marginTop: '24px' }}>
        <Form
          layout="horizontal"
          labelWidth={100}
          onSubmit={handleFormSubmit}
        >
          <ldesign-form-item label="用户名" name="username" required>
            <ldesign-input placeholder="请输入用户名" />
          </ldesign-form-item>

          <ldesign-form-item label="邮箱" name="email" required>
            <ldesign-input type="email" placeholder="请输入邮箱" />
          </ldesign-form-item>

          <ldesign-form-item>
            <Button type="primary" htmlType="submit">
              提交
            </Button>
          </ldesign-form-item>
        </Form>
      </Card>
    </div>
  );
}

export default App;

// www/examples/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { defineButton, defineTable, defineCard, defineForm } from '@ldesign/webcomponent-vue';

// 按需导入组件
defineButton();
defineTable();
defineCard();
defineForm();

// 表格数据
const columns = ref([
  { key: 'id', title: 'ID', width: 60, sortable: true },
  { key: 'name', title: '姓名', sortable: true },
  { key: 'age', title: '年龄', width: 80, sortable: true },
  { key: 'email', title: '邮箱' }
]);

const dataSource = ref<any[]>([]);

// 表单数据
const formData = ref({
  username: '',
  email: '',
  password: ''
});

// 生成大量测试数据
onMounted(() => {
  dataSource.value = Array.from({ length: 5000 }, (_, i) => ({
    id: i + 1,
    name: `用户 ${i + 1}`,
    age: 20 + (i % 40),
    email: `user${i + 1}@example.com`
  }));
});

const handleSort = (e: CustomEvent) => {
  const { key, order } = e.detail;
  console.log('排序:', key, order);
};

const handleSubmit = async (e: CustomEvent) => {
  console.log('表单提交:', e.detail);
  alert('提交成功！');
};

const handleButtonClick = () => {
  alert('按钮被点击！');
};
</script>

<template>
  <div class="app">
    <h1>LDesign WebComponent - Vue 3 示例</h1>

    <!-- 按钮示例 -->
    <ldesign-card title="按钮示例">
      <div class="button-group">
        <ldesign-button type="primary" @ldesignClick="handleButtonClick">
          Primary
        </ldesign-button>
        <ldesign-button type="success">Success</ldesign-button>
        <ldesign-button type="warning">Warning</ldesign-button>
        <ldesign-button type="danger">Danger</ldesign-button>
      </div>
    </ldesign-card>

    <!-- 表格示例 -->
    <ldesign-card title="数据表格（虚拟滚动 5000 行）" style="margin-top: 24px;">
      <ldesign-table
        :columns="JSON.stringify(columns)"
        :dataSource="JSON.stringify(dataSource)"
        bordered
        striped
        virtual
        height="400"
        row-height="48"
        @ldesignSort="handleSort"
      />
    </ldesign-card>

    <!-- 表单示例 -->
    <ldesign-card title="表单示例" style="margin-top: 24px;">
      <ldesign-form 
        layout="horizontal"
        label-width="100"
        @ldesignSubmit="handleSubmit"
      >
        <ldesign-form-item label="用户名" name="username" required>
          <ldesign-input 
            v-model="formData.username"
            placeholder="请输入用户名"
          />
        </ldesign-form-item>

        <ldesign-form-item label="邮箱" name="email" required>
          <ldesign-input 
            v-model="formData.email"
            type="email"
            placeholder="请输入邮箱"
          />
        </ldesign-form-item>

        <ldesign-form-item>
          <ldesign-button type="primary" html-type="submit">
            提交
          </ldesign-button>
        </ldesign-form-item>
      </ldesign-form>
    </ldesign-card>
  </div>
</template>

<style scoped>
.app {
  padding: 24px;
  max-width: 1200px;
  margin: 0 auto;
}

.button-group {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

h1 {
  color: var(--ld-color-primary);
  margin-bottom: 24px;
}
</style>
